#JPA PROPERTIES
spring:
  jpa:
      database: POSTGRESQL
      show-sql: true
      hibernate:
        ddl-auto: none
        #create-drop
---
#DATABASE
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/findtrip-db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

---
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false







