#Configuration
server:
  servlet:
    context-path: /api
---
#JPA PROPERTIES
spring:
  jpa:
      database: POSTGRESQL
      show-sql: true
      hibernate:
        ddl-auto: none
        #create-drop
---
#DATABASE
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/findtrip-db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

---
#Thymeleaf
spring:
  thymeleaf:
    mode: HTML
    cache: false

---
#Log4j
logging:
  file:
    name: C:\Users\alekot\Desktop\kotkovets\findtrip\src\main\resources\logs\dev_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.howtodoinjava: DEBUG
    org.hibernate: ERROR





